### ISSUE TITLE
ang in make_pol_grid is a float and doesn't have reshape method

### ISSUE THREAD

**Issue by RichardPflaum** [jacopoantonello/zernike#1]
Hi, I just cloned this and am trying to understand the module, but my Linter is complaining:
The line `ang = self.angular(k, theta_i).reshape((L, 1), order='F') ` in the method make_pol_grid  seems to be wrong, since self.angular returns a float.

**Comment by RichardPflaum** [comment]
Sorry, nevermind this must be a Pylint issue.

**Comment by RichardPflaum** [comment]
The issue is caused by the `angular` method in the baseclass. This can be fixed using `ABCMeta` as `metaclass` for Zern and using the `@abstractmethod` decorator for angular instead of simply returning 0.

**Comment by jacopoantonello** [comment]
Hi. Could you please check whether a1d85c32eb3256ca62fab253ef53269326044cbe fixes this problem? My linter didn't show any warning, so I can't reproduce this. Thank you.

**Comment by RichardPflaum** [comment]
Looks good! I'll check it tomorrow.

**Comment by RichardPflaum** [comment]
Yes that does it. Thanks!
