### ISSUE TITLE
pip2 version 0.0.0 instead of 0.0.30

### ISSUE THREAD

**Issue by adriaanph** [jacopoantonello/zernike#11]
thanks for the recent changes - very useful.

i have just attempted to install using pip2 (python2), but the version number is 0.0.0 instead of 0.0.30. doing the same using pip3 (python3) correctly shows it as 0.0.30.

in the end i opted to install from git instead of pip. this installed the correct code and the version is now correct.

here are the steps i followed to install from github:
`  $ git clone https://github.com/jacopoantonello/zernike`
`  $ pip2 install zernike`

**Comment by jacopoantonello** [comment]
Related to #12 . [Here](https://github.com/jacopoantonello/zernike/blob/39e590252758dbd9ac6fcbec91b041c42fb747d5/setup.py#L34) 0.0.0 is used if `setup.py` cannot determine the version automatically (e.g. there's no tags or git is not installed). Doesn't `pip2 install zernike` work with the already made package downloaded from pypi? Why do you need to make the package again from the source code?

**Comment by adriaanph** [comment]
from my opening post:
> i have just attempted to install using pip2 (python2), but the version number is 0.0.0 instead of 0.0.30. doing the same using pip3 (python3) correctly shows it as 0.0.30.

to be clear: `pip2 install zernike` results in version being reported as 0.0.0

**Comment by adriaanph** [comment]
i don't have any experience with pypi but perhaps there's something wrong with the way in which you publish to pypi for python 2?

**Comment by jacopoantonello** [comment]
Can you check whether now you can install with `pip2 install zernike`? I don't have Python 2

**Comment by adriaanph** [comment]
it works now! 0.0.31 is correctly installed using `pip2 install zernike`.
i see you added the "--universal" switch to build the "wheel" with. good to know it was something so simple!
