### ISSUE TITLE
H5PY dependencies

### ISSUE THREAD

**Issue by dkimanius** [jacopoantonello/zernike#16]
I got: `ModuleNotFoundError: No module named 'h5py'`
at line: `from zernike import RZern`

So H5PY dependency was not installed along wiht zernike when using pip install. I see it in the setup.py setup_requires, so not sure exactly why this happens. In Ubuntu, I started from a fresh conda environment with:

```
$ conda create -n <name> python=3.9
$ pip3 install torch torchvision torchaudio
$ pip install zernike
```

**Comment by jacopoantonello** [comment]
I changed `setup_requires` to `install_requires` and that seems to work for me. Is that working for you too? Using the latest version (0.0.33)?

**Comment by dkimanius** [comment]
Seems to be working!
