### ISSUE TITLE
Question about fitting

### ISSUE THREAD

**Issue by shz224** [jacopoantonello/zernike#4]
Thanks for your code. I have a problem with fitting a complex array. Could you please give an example of fitting with data generated by ways except eval_grid()?

**Comment by jacopoantonello** [comment]
Fitting a complex array works for polar coordinates, see the last example in the home page (Example: fit Zernike polynomials in polar coordinates) and the test using complex data [here](https://github.com/jacopoantonello/zernike/blob/384d2b8737f19c5e228b094645c73037cfa286b7/tests/test_czernike.py#L486). I'm not sure the code currently works for Cartesian coordinates, but it should be relatively easy to implement.

**Comment by shz224** [comment]
OK, thanks a lot for your reply.
