### ISSUE TITLE
Zernike polynomial fitting from 3-D coordinates?

### ISSUE THREAD

**Issue by sidgairo18** [jacopoantonello/zernike#6]
Hi, supposing as input we have a set of 3-D points (x,y,z) that lie on a 3 dimensional surface.
How would the zernike fitting function work in this case? From the examples it is not apparent what the input should be exactly.
Would be grateful for your help.
Thank you.

**Comment by jacopoantonello** [comment]
Hi! Perhaps you should look at [orthopy](https://github.com/nschloe/orthopy) instead. This toolbox only support regular Zernike polynomials on a unit disk.

**Comment by sidgairo18** [comment]
Thank you for your response @jacopoantonello . Wouldn't scaling the 3-D points (x,y,z) to a unit vector make the points to lie on a unit disk?
Then can it be used with your fitting function?
